# problem 12
# highly divisible triangle number
"""
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

1:  1: 1
2:  3: 1,3
3:  6: 1,2,3,6
4: 10: 1,2,5,10
5: 15: 1,3,5,15
6: 21: 1,3,7,21
7: 28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""

def summation(x):
    return sum(i+1 for i in range(x))

def number_of_factors(x):
    count = 1
    for factor in range(x//2, 2, -1):
        if x % factor == 0:
            print(factor)
            count += 1
    return count
for i in range(1, 11):
    x = summation(i)
    print(x, number_of_factors(x))
x = 8
# factors = number_of_factors(summation(x))
# while factors < 500:
#     x += 1
#     factors = number_of_factors(summation(x))
# print(x)
print(number_of_factors(summation(1001001)))
