# problem 2
# Even Fibonacci numbers
# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#       1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not 
# exceed four million, find the sum of the even-valued terms.

def fib(x):
    a, b = 0, 1
    while a < x:
        yield a
        a, b = b, a + b
print(sum(f for f in fib(4000000) if f % 2))

def even_fib(x):
    sum = 0
    a, b, c = 1, 1, 2
    while c < x:
        print(c)
        sum = sum + c
        a = b + c
        b = a + c
        c = a + b
    return sum
print(even_fib(90))